[workspace]
members = [
    "render",
    "view",
]

[patch."https://github.com/servo/pathfinder"]
pathfinder_gl = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_webgl = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_gpu = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_color = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_renderer = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_resources = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_export = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_simd = { git = "https://github.com/s3bk/pathfinder" }

[patch.crates-io]
pathfinder_gl = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_webgl = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_gpu = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_color = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_renderer = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_resources = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_export = { git = "https://github.com/s3bk/pathfinder" }
pathfinder_simd = { git = "https://github.com/s3bk/pathfinder" }
